### ISSUE TITLE
Allow a looping Tone.Player to start before loopStart

### ISSUE THREAD

**Issue by hiddedejong** [TONEnoTONE/Tone.js#76]
When `loop` is set to `true`, `Tone.Player` starts the buffer playback at the `loopStart` position. It would be very nice to be able to set a different starting position. This will result in, for example, the ability to start the playback at bar 1, but make the player loop between bar 4 and bar 9. 

The Web Audio API supports this by setting the start method's`offset` to a different value than loopStart. It looks like `Tone.Player` already supports this internally, but there is not way to call `start()` with a user-defined offset.

**Comment by tambien** [comment]
Thanks for the comment Hidde. Tone.Player does support offset and duration just like the native AudioSourceBufferNode. The interface is also pretty similar to the native node. 

`player.start(undefined, 0)` will start the player immediately at the offset 0 (the start) regardless of what the `loopStart` is set to. If no offset is given, then it will default to the `loopStart`.

You highlight a good point which is that it's entirely undocumented because Tone.Source defines the `start` method and passes it's arguments to the Player's [private start method](https://github.com/TONEnoTONE/Tone.js/blob/3279e02c9233d22f8696bafb8b2d77aa53cd68fe/Tone/source/Player.js#L154). i'll find a way to expose that documentation.

**Comment by hiddedejong** [comment]
Thanks!
